import React from "react";
import { useRouter } from "next/router";
import Image from "next/image";
import Head from "next/head";

// import projectData from "../../data/data";
import SpaceTourism from "../../projects/SpaceTourism";
import ImageUploader from "../../projects/ImageUploader";
import { nameParser } from "../../utils/parsers";

const CurrentProject = ({ projectName }) => {
  switch (projectName) {
    case "Space Tourisms":
      return <SpaceTourism />;
    case "Image Uploader":
      return <ImageUploader />;
    default:
      return <Image src="/assets/404page.gif" layout="fill" alt="404 page" />;
  }
};

const ProjectName = (props) => {
  const router = useRouter();
  const { projectName } = router.query;
  const parsedProjectName = nameParser(projectName);
  return (
    <div>
      <Head>
        <title>{projectName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`/assets/${parsedProjectName}/favicon-32x32.png`} />
      </Head>
      <CurrentProject projectName={projectName} />
    </div>
  );
};
export default ProjectName;

// export async function getStaticPaths() {
//   return {
//     paths: [
//       {
//         params: {
//           projectName: "space-tourisms",
//         },
//       },
//       {
//         params: {
//           projectName: "image-uploader",
//         },
//       },
//     ],
//     fallback: false, // false or 'blocking'
//   };
// }

// export async function getStaticProps(context) {
//   const { projectName } = context.params;
//   const parsedProjectName = projectNameParser(projectName);
//   const projects = projectData();
//   return {
//     props: projects, // will be passed to the page component as props
//   };
// }
