import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const encodeUrl = (project) => {
  return project.toLowerCase().split(" ").join("-");
};

export default function Home() {
  const projects = ["Space Tourisms"];
  return (
    <div className={styles.container}>
      <Head>
        <title>Showcase Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.button_container}>
          {projects.map((project, i) => {
            const encodedUrl = encodeUrl(project);
            return (
              <Link href={`/${encodedUrl}`} key={i}>
                <a className={styles.link_to_project}>{project}</a>
              </Link>
            );
          })}
        </div>
        <div className={styles.carousel}>
          {projects.map((project, i) => {
            const encodedUrl = encodeUrl(project);
            return (
              <Link key={i} href={`/${encodedUrl}`}>
                <Image
                  className={styles.image}
                  src="/assets/spaceTourisms/Desktop-Home.jpg"
                  alt="space tourism image"
                  height={400}
                  width={700}
                />
              </Link>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
