import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const encodeUrl = (project) => {
  return project.toLowerCase().split(" ").join("-");
};

export default function Home() {
  const projects = ["Space Tourisms"];
  return (
    <div className={styles.container}>
      <Head>
        <title>Showcase Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.buttonContainer}>
          {projects.map((project, i) => {
            const encodedUrl = encodeUrl(project);
            return (
              <Link href={`/${encodedUrl}`} key={i}>
                {project}
              </Link>
            );
          })}
        </div>
        <div>
          <Link href='/space-tourisms'>
          <Image
          className={styles.image}
            src="/assets/spaceTourisms/Desktop-Home.jpg"
            alt="space tourism image"
            height={500}
            width={900}
          />
          </Link>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
